### ISSUE TITLE
Just me or does this syntax make base16 color schemes very red?

### ISSUE THREAD

**Issue by TheIronBorn** [colinta/Swift-for-f-ing-sublime#10]
Using `Swift-for-f-ing-sublime` on the left, and the same code in C using Sublime's default syntax on the right.
![screen shot 2017-01-10 at 20 15 57](https://cloud.githubusercontent.com/assets/7707250/21836387/b7d2c4d6-d779-11e6-8278-270766ad6c3a.png)
Maybe it's just a matter of preference but it seems odd to me.

**Comment by colinta** [comment]
Ew that looks terrible - can you tell me what the language grammar is at some of those places? (ctrl + shift + P I think). I'll try to take a look later.

**Comment by TheIronBorn** [comment]
It's all `variable.other` except for function parameter names:
![screen shot 2017-01-12 at 17 07 02](https://cloud.githubusercontent.com/assets/7707250/21914695/b8981ce2-d8e9-11e6-963d-b18316e553f7.png)
![screen shot 2017-01-12 at 17 07 20](https://cloud.githubusercontent.com/assets/7707250/21914697/bd562166-d8e9-11e6-9575-87bb0d0b2238.png)

And here's a function argument:
![screen shot 2017-01-12 at 17 07 22](https://cloud.githubusercontent.com/assets/7707250/21914702/c107cd46-d8e9-11e6-9faa-9c8e92534e1d.png)

- MacBook Pro (13-inch, Early 2011)
- macOS 10.12.2
- Sublime Text: Stable Channel, Build 3126
- Swift-for-f-ing-sublime: v2.3.4

**Comment by colinta** [comment]
Gotcha, well I think this could be easy; there's only one place where I defined `variable.other`, and I think we could just remove it and try this out!  Can you tell me more about the base 16 color scheme?  I'll download the one you're using.

**Comment by colinta** [comment]
```diff
diff --git a/Swift.sublime-syntax b/Swift.sublime-syntax
index 6d34503..32b355e 100644
--- a/Swift.sublime-syntax
+++ b/Swift.sublime-syntax
@@ -128,8 +128,6 @@ contexts:
     - match: '(\w+):'
       captures:
         1: variable.parameter
-    - match: \b\w+
-      scope: variable.other
     - match: '[-+=<>^$#@!~*\\|&?\/.]*'
       scope: keyword.operator
     - match: '\('
```

I think that did it!

Before:
<img width="439" alt="screen shot 2017-01-12 at 8 01 39 pm" src="https://cloud.githubusercontent.com/assets/27570/21917043/0b6a9720-d902-11e6-8d86-18a6f8b363c8.png">

After:
<img width="429" alt="screen shot 2017-01-12 at 8 01 19 pm" src="https://cloud.githubusercontent.com/assets/27570/21917044/0dcee494-d902-11e6-993b-5d62457b9828.png">

**Comment by colinta** [comment]
Try it out in v2.3.5

**Comment by TheIronBorn** [comment]
Yup seems to have fixed it. Thanks!

I was using [Spacegray's Eighties theme](https://github.com/kkga/spacegray/blob/master/base16-eighties.dark.tmTheme) which is a fork of [chriskempson's](https://github.com/chriskempson/base16-textmate/blob/master/Themes/base16-eighties.tmTheme).

**Comment by colinta** [comment]
Great!  Please close this issue if it's been resolved.
