### ISSUE TITLE
2.0.1 breaks syntax highlighting

### ISSUE THREAD

**Issue by nrw** [colinta/Swift-for-f-ing-sublime#2]
when the package control auto-update installed 2.0.1 in ST3, swift syntax highlighting disappeared. 2.0.0 was working well.

**Comment by nrw** [comment]
correction: 1.1.1 was working well. 2.0.0 broke syntax highlighting for me.

**Comment by colinta** [comment]
Using ST3?

**Comment by nrw** [comment]
yes. sublime text 3, build 3083.

**Comment by colinta** [comment]
I dunno, that's just odd.  I'm able to install using Package Control or by cloning the source, and both ways seem to be working.  Can you investigate more, or send me more details?  Is the package installed, but nothing is colored?  Have you tried installing it via source?

**Comment by colinta** [comment]
Ah, you need to upgrade to build 3084

**Comment by colinta** [comment]
I updated the package.json to require the correct version.  Thanks for telling me the build number, that was the missing key!

**Comment by nrw** [comment]
that solved it. thanks!
