### ISSUE TITLE
Get source.swift invalid when I shouldn't

### ISSUE THREAD

**Issue by oddysee** [colinta/Swift-for-f-ing-sublime#5]
I'm not entirely sure how to describe this but I'm seeing red highlighted areas which don't make sense -

<img width="494" alt="screen shot 2016-05-31 at 5 13 12 pm" src="https://cloud.githubusercontent.com/assets/899902/15666252/28b1af50-2753-11e6-8261-bea94730f0c0.png">

Why would this be invalid? 

<img width="1085" alt="screen shot 2016-05-31 at 5 15 24 pm" src="https://cloud.githubusercontent.com/assets/899902/15666285/53ef1414-2753-11e6-9c65-80849035ea0c.png">

**Comment by colinta** [comment]
Ok, someone else saw this same thing - it doesn't happen locally, which is even stranger!  I started a rewrite of this syntax anyway, I'll make sure this gets addressed, too.

Are you using version 2.2.4?  I'm going to overwrite that version with a *reverted* version (e.g. 2.2.3 will become 2.2.5).  There was too much wrong with my original attempt at a rewrite.

**Comment by oddysee** [comment]
I'm using 2.3.0. Let me know if you need me to try anything. And thanks for you work on this... I've switched to using ST3 for most of my iOS dev thanks to your awesome work 😄

**Comment by oddysee** [comment]
Closing since this has been fixed with the release of 2.3.1 (which essentially reverted everything back to 2.2.4)
