### ISSUE TITLE
swift struct can have parent. So, it is not invalid.

### ISSUE THREAD

**Issue by hiking90** [colinta/Swift-for-f-ing-sublime#6]
Hello,

I'm using this plugin and I think this plugin's approach is better than other swift support plugin.
Thank you.

Like this title, struct can have protocol parent. I've tested it on Swift 3.0 preview.

Example is :
struct Exception : ErrorProtocol {
....
}

Regards,
Jeff

**Comment by colinta** [comment]
Oh shoot, good point!

**Comment by colinta** [comment]
Fixed (finally!) in 2.3.4
