### ISSUE TITLE
Goto Symbol doesn't work

### ISSUE THREAD

**Issue by akrabat** [colinta/Swift-for-f-ing-sublime#9]
Goto Symbol in Project shows all the classes with the word `class ` prepended. This means that the keyboard shortcut doesn't work.

![screen shot 2017-01-03 at 09 02 00](https://cloud.githubusercontent.com/assets/33135/21603213/51432c4c-d193-11e6-8df9-8548ca099113.png)

**Comment by colinta** [comment]
Are you saying you don't think classes/protocols/structs should be in the Goto Symbol list?

**Comment by akrabat** [comment]
No,
I'm saying that the world "class " shouldn't be there.

**Comment by colinta** [comment]
Ahh, I see.  I actually use that to help me filter a file's symbols - e.g. it makes it easy to look at all the classes in a file.

I consider this a feature, so I won't be removing it, but there is an "official" sublime language definition coming out, you might want to keep an eye on its progress.

**Comment by akrabat** [comment]
Thanks. That's a shame as I use `shift+cmd+down` all the time :(

**Comment by colinta** [comment]
What does cmd+shift+down do?  Something function related, I assume, but on my setup that's "select from the cursor to the end of the file".  I use "cmd+shift+J" to "select body", which works on conditionals, loops, methods, and classes (I think it's based on indentation).

**Comment by colinta** [comment]
I looked into how you could implement this change in a fork: just remove `scope: entity.name.type` from the two places that mention `enum|class|struct|protocol|extension`.

```diff
diff --git a/Swift.sublime-syntax b/Swift.sublime-syntax
index 6d34503..76f11b0 100644
--- a/Swift.sublime-syntax
+++ b/Swift.sublime-syntax
@@ -60,7 +60,6 @@ contexts:
     - match: \b(class)\s+(?=func)
       scope: meta.function storage.type.function
     - match: \b(enum|class|struct|protocol|extension)\s+((\w+)\s*(:)\s+(\w+))
-      scope: entity.name.type
       captures:
         1: keyword.entity
         2: entity.name.type
@@ -68,7 +67,6 @@ contexts:
         4: keyword.operator
         5: support.class
     - match: \b(enum|class|struct|protocol|extension)\s+(\w+)
-      scope: entity.name.type
       captures:
         1: keyword.entity
         2: entity.name.type support.class
```

I Hope this helps!

**Comment by akrabat** [comment]
Sorry - I misremembered what my hands do :). I meant `alt+cmd+down`. It jumps me directly to the function under the caret.

**Comment by akrabat** [comment]
I didn't know about `cmd+shift+J` - Thanks!

Thanks for pointing out the code - I'll have a play.

**Comment by zydeon** [comment]
My Goto symbol list is always empty. I'm using build 3143. Is this feature still supported?

**Comment by colinta** [comment]
Strange! Yes I use it all the time. 

Double check the package. None of the other Swift language packages have goto-symbol, make sure you’re using this one.
